"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let ModifiedGuestList = ['Rumana', 'Maqbool', 'Salaar', `Amrina`, `Rasheeda`];
console.log("You've Invited to Dinner at sharp 9:00: " + ModifiedGuestList[0]);
console.log("You've Invited to Dinner at sharp 9:00: " + ModifiedGuestList[1]);
console.log("You've Invited to Dinner at sharp 9:00: " + ModifiedGuestList[2]);
console.log("You've Invited to Dinner at sharp 9:00: " + ModifiedGuestList[3]);
console.log("Thanks for your invitation but im not able to accept that invitation due to some issues: \n Regards:" + ModifiedGuestList[2]);
console.log("Modified List Of the Guests are;\n");
let ModifiedGuestList4 = ['Rumana', 'Maqbool', 'Salaar', `Amrina`, `Rasheeda`];
console.log("You've Invited to Dinner at sharp 9:00: " + ModifiedGuestList4[0]);
console.log("You've Invited to Dinner at sharp 9:00: " + ModifiedGuestList4[1]);
console.log("You've Invited to Dinner at sharp 9:00: " + ModifiedGuestList4[2]);
console.log("You've Invited to Dinner at sharp 9:00: " + ModifiedGuestList4[3]);
