let Name:String[];
Name=[`Abdul Ghafoor`,`Rasheeda`,'Rumana','Maqbool','Salaar',`Amrina`,`Ayya`,`Rehan`,`Rizwana`,`Imran`];
console.log(Name[0]);
console.log(Name[1]);
console.log(Name[2]);
console.log(Name[3]);
console.log(Name[4]);
console.log(Name[5]);
console.log(Name[6]);
console.log(Name[7]);
console.log(Name[8]);
console.log(Name[9]);
